# Default values for ticket-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  backend: 1
  frontend: 1

image:
  backend:
    repository: 488363440930.dkr.ecr.ap-northeast-1.amazonaws.com/ticket-management-backend-dev
    pullPolicy: IfNotPresent
    tag: "43f349a75f0be113bc02082df84ca5c1eaf00fef"
  frontend:
    repository: 488363440930.dkr.ecr.ap-northeast-1.amazonaws.com/ticket-management-frontend-dev
    pullPolicy: IfNotPresent
    tag: "43f349a75f0be113bc02082df84ca5c1eaf00fef"

# ArgoCD Image Updater configuration
argocdImageUpdater:
  backend:
    allowTags: "^[a-fA-F0-9]+$"
    updateStrategy: "version"
  frontend:
    allowTags: "^[a-fA-F0-9]+$"
    updateStrategy: "version"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: ae61e6110ead2413e8e7d119b5b871f9-1708833654.ap-northeast-1.elb.amazonaws.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: ticket-demo-tls
  #    hosts:
  #      - ticket-demo.local

resources:
  backend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  frontend:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}