# Production values for ticket-system.

replicaCount:
  backend: 3
  frontend: 3

image:
  backend:
    repository: 488363440930.dkr.ecr.ap-northeast-1.amazonaws.com/ticket-management-backend-dev
    tag: "latest"
  frontend:
    repository: 488363440930.dkr.ecr.ap-northeast-1.amazonaws.com/ticket-management-frontend-dev
    tag: "latest"

resources:
  backend:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  frontend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

ingress:
  hosts:
    - host: ticket.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ticket-tls
      hosts:
        - ticket.yourdomain.com

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70