apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ticket-management-prod
  annotations:
    config.kubernetes.io/local-config: "true"

bases:
  - ../../base

namespace: ticket-prod

replicas:
  - name: backend-deployment
    count: 2
  - name: frontend-deployment
    count: 2

images:
  - name: 488363440930.dkr.ecr.ap-northeast-1.amazonaws.com/ticket-management-backend
    newTag: placeholder
  - name: 488363440930.dkr.ecr.ap-northeast-1.amazonaws.com/ticket-management-frontend
    newTag: placeholder

patchesStrategicMerge:
  - backend-prod-config.yaml
  - frontend-prod-config.yaml

resources:
  # 可以在这里添加prod专用的资源，比如Ingress等