apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane # master节点
    # port forward 30000 on the host to 30000 on this node
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        # Optional, defaults to "0.0.0.0"
        listenAddress: "0.0.0.0"
        # Optional, defaults to tcp
        protocol: tcp
      - containerPort: 31321
        hostPort: 31321
      - containerPort: 31300
        hostPort: 31300
  - role: worker # worker从节点
  - role: worker