apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticket-system.fullname" . }}-backend
  labels:
    {{- include "ticket-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ticket-system.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend