apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ticket-dev
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort