name: CD to Production

on:
  push:
    tags: [ 'v*' ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy to Production
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: 'v3.13.0'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG_PROD }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Deploy with Helm
      run: |
        export KUBECONFIG=kubeconfig
        cd cicd/helm/ticket-system

        # Deploy to production
        helm upgrade --install ticket-system . \
          --namespace ticket-prod \
          --create-namespace \
          --values values-prod.yaml \
          --wait \
          --timeout 10m

    - name: Verify Deployment
      run: |
        export KUBECONFIG=kubeconfig
        helm status ticket-system -n ticket-prod
        kubectl get pods -n ticket-prod