apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticket-system-dev
  namespace: argocd
  annotations:
    # ArgoCD Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: backend=488363440930.dkr.ecr.ap-northeast-1.amazonaws.com/ticket-management-backend-dev,frontend=488363440930.dkr.ecr.ap-northeast-1.amazonaws.com/ticket-management-frontend-dev
    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[a-fA-F0-9]{40}$
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^[a-fA-F0-9]{40}$
spec:
  project: ticket-system
  source:
    repoURL: https://github.com/uniquejava/play-cicd001.git
    targetRevision: main
    path: cicd/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ticket-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true