name: CI Pipeline - Dev

on:
  push:
    branches: [ develop ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'cicd/docker/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'cicd/docker/**'

env:
  AWS_REGION: ap-northeast-1
  ECR_REGISTRY: 488363440930.dkr.ecr.ap-northeast-1.amazonaws.com

jobs:
  test-backend:
    runs-on: ubuntu-latest
    name: Test Backend

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run backend tests
      working-directory: ./backend
      run: mvn test

    - name: Build backend JAR
      working-directory: ./backend
      run: mvn clean package -DskipTests

  test-frontend:
    runs-on: ubuntu-latest
    name: Test Frontend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10.18.2

    - name: Install dependencies
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile

    - name: Run frontend tests
      working-directory: ./frontend
      run: pnpm test

    - name: Build frontend
      working-directory: ./frontend
      run: pnpm build

  build-and-push-images:
    runs-on: ubuntu-latest
    name: Build and Push Docker Images
    needs: [test-backend, test-frontend]
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
      continue-on-error: true

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      continue-on-error: true

    - name: Build and push backend image
      if: steps.login-ecr.outputs.registry != ''
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./cicd/docker/backend/Dockerfile
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/ticket-management-backend-dev:${{ env.IMAGE_TAG }}

    - name: Build and push frontend image
      if: steps.login-ecr.outputs.registry != ''
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./cicd/docker/frontend/Dockerfile
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/ticket-management-frontend-dev:${{ env.IMAGE_TAG }}

    - name: Image build summary
      run: |
        if [ "${{ steps.login-ecr.outputs.registry }}" != "" ]; then
          echo "✅ Backend image: ${{ env.ECR_REGISTRY }}/ticket-management-backend-dev:${{ env.IMAGE_TAG }}"
          echo "✅ Frontend image: ${{ env.ECR_REGISTRY }}/ticket-management-frontend-dev:${{ env.IMAGE_TAG }}"
          echo "📝 Note: Manual deployment required. Use kubectl set image to update deployments."
        else
          echo "⚠️ AWS credentials not configured - images built locally only"
          echo "🔧 To enable ECR push, configure AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in repository secrets"
        fi